shop/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from shop.views import *
from contact.views import ContactCreate
from user.views import *
from newsletters.views import send
from cart.views import *
from category.views import *
from item.views import get_item, fetch_items_from_amazon, filter_items
from profiles.views import *
from order.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Home.as_view(), name='home'),
    url(r'^contact/$', ContactCreate, name='contact'),
    url(r'^about$', About.as_view(), name='about'),
    url(r'^login/$', login_in, name="log in"),
    url(r'^newsletters/$', send, name="newsletters"),
    url(r'^cart/$', show, name="cart"),
    url(r'^category/$', cat, name="categories"),
    url(r'^product-filter/$', filter_items, name="filter"),
    url(r'^category/(?P<slug>[-\w]+)/$', categories_child_list, name="child categories list"),
    url(r'^category/(?P<slug>[-\w]+)/(?P<child_slug>[-\w]+)/$', category_by_slug, name="category view"),
    url(r'^category/(?P<slug>[-\w]+)/(?P<child_slug>[-\w]+)/(?P<page>[\d]+)/$', category_by_slug, name="category page"),
    url(r'^category/(?P<slug>[-\w]+)/(?P<child_slug>[-\w]+)/(?P<product_slug>[-\w]+)/$', get_item, name="product"),
    url(r'^amazon/$', get_amazon, name="amazon"),
    url(r'^search/', include('search.urls')),
    url(r'^register/$', register, name='register'),
    url(r'^parse/$', fetch_items_from_amazon, name="parse"),
    url(r'^account/$', Account.as_view(), name='account'),
    url(r'^account/edit/$', edit_account, name='edit'),
    url(r'^add/$', add, name='add'),
    url(r'^order/$', order, name='order'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^remove/$', remove, name='remove')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from item.models import Item
from order.models import UserOrder


class CartOrder(models.Model):
    item_id = models.ForeignKey(Item)
    order_id = models.IntegerField(blank=True, null=True)
    quantity = models.IntegerField()

    def __str__(self):
        return 'Order id: {}'.format(self.order_id)
# Create your models here.

order/models.py
from django.db import models
from user.models import User
from delivery.models import Delivery
from payment.models import Payment

COUNTRIES = (
    ('GB', 'United Kingdom'),
    ('AF', 'Afghanistan'),
    ('AL', 'Albania'),
    ('DZ', 'Algeria'),
    ('AS', 'American Samoa'),
    ('AD', 'Andorra'),
    ('AR', 'Argentina'),
    ('AM', 'Armenia'),
    ('AU', 'Australia'),
    ('AT', 'Austria'),
    ('BY', 'Belarus'),
    ('BE', 'Belgium'),
    ('BZ', 'Belize'),
    ('BM', 'Bermuda'),
    ('LT', 'Lithuania'),
    ('LU', 'Luxembourg'),
    ('RU', 'Russian Federation'),
    ('US', 'United States'),
)


class UserOrder(models.Model):
    cart_id = models.IntegerField(blank=True, null=True)
    user_id = models.ForeignKey(User, blank=True, null=True)
    status = models.CharField(blank=True, null=True, max_length=255)
    delivery_id = models.ForeignKey(Delivery)
    summary = models.IntegerField()
    email = models.CharField(blank=True, null=True, max_length=255)
    payment_id = models.ForeignKey(Payment)
    first_name = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    first_line_adress = models.CharField(max_length=255, blank=True, null=True)
    country = models.CharField(choices=COUNTRIES, max_length=100, blank=True, null=True)
    postal_code = models.CharField(max_length=10, blank=True, null=True)

    def __str__(self):
        return 'Order $ {}, id: {}, status: {}'.format(self.summary, self.id, self.status)
# Create your models here.

cart/views.py
from django.shortcuts import render, HttpResponse
from django.views.generic import TemplateView
from carton.cart import Cart
from item.models import Item
import json


def add(request):
    cart = Cart(request.session)
    item = Item.objects.get(id=request.POST.get('id'))
    cart.add(item, price=item.price)
    response = {
        'status': 'true',
        'message': 'OK',
        'count': cart.count
    }
    return HttpResponse(json.dumps(response), content_type='application/javascript; charset=utf8', status=200)


def remove(request):
    cart = Cart(request.session)
    product = Item.objects.get(id=request.POST.get('id'))
    cart.remove(product)
    return render(request, 'cart/cart-ajax.html')


def show(request):
    return render(request, 'cart/cart.html')
# Create your views here.

order/views.py
from django.shortcuts import render
from .models import UserOrder
from django.contrib.auth.models import User
from cart.models import CartOrder
from delivery.models import Delivery
from payment.models import Payment
from carton.cart import Cart
from item.models import Item


def order(request):
    if request.method == 'POST':
        context = {}
        cart = Cart(request.session)

        summary = cart.total
        delivery = request.POST.get('delivery')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        first_line_adress = request.POST.get('first_line_adress')
        city = request.POST.get('city')
        postal_code = request.POST.get('postal_code')
        country = request.POST.get('country')
        email = request.POST.get('email')
        paymentMethod = request.POST.get('paymentMethod')

        if request.user.is_authenticated():
            user = User.objects.get(id=request.user.id)
            user.first_name = first_name
            user.last_name = last_name
            user.email = email
            user.save()

        order = UserOrder.objects.create(status='Pending', delivery_id_id=delivery,
                                         payment_id_id=paymentMethod, first_name=first_name, email=email, user_id_id=request.user.id,
                                         city=city, country=country, first_line_adress=first_line_adress,
                                         postal_code=postal_code, summary=summary)

        for item in cart.items:
            product = Item.objects.get(id=item.product.id)
            product.quantity -= item.quantity
            product.save()
            CartOrder.objects.create(order_id=order.id, item_id_id=item.product.id, quantity=item.quantity)

        cart.clear()

        return render(request, "cart/thanks.html", context)
    else:
        context = {}
        context['delivery'] = Delivery.objects.all()
        context['payment'] = Payment.objects.all()
        return render(request, 'cart/order.html', context)
# Create your views here.

templates/cart/cart-ajax.html
{% load carton_tags %}
{% get_basket as my_basket %}
        <div class="cart__caption">
            <h1>Your shopping bag</h1>
            {% if my_basket.count == 0 %}
            <p>is empty</p>
            {% else %}
            <p>Items reserved for limited time only</p>
            {% endif %}
        </div>
        {% if my_basket.count > 0 %}
        <div class="cart__order">
            <div class="order-quality">
                <div class="order-quality__product cart__product-block">
                    <p>Product</p>
                </div>
                <div class="order-quality__description cart__product-block">
                    <p>Description</p>
                </div>
                <div class="order-quality__color cart__product-block">
                    <p>Color</p>
                </div>
                <div class="order-quality__quantity cart__product-block">
                    <p>Qty</p>
                </div>
                <div class="order-quality__amount cart__product-block">
                    <p>Amount</p>
                </div>
                <div class="order-quality__size cart__product-block">
                    <p>Subtotal</p>
                </div>
                <div class="order-quality__amount cart__product-block">
                    <p>Remove</p>
                </div>
            </div>
            {% for item in my_basket.items %}
                <div class="cart__product">
                    <div class="product__image cart__product-block">
                        <img src="/dist/img/item/{{ item.product.thumbnail_image }}">
                    </div>
                    <div class="product__caption cart__product-block">
                        <a href="{% url "product" child_slug=item.product.category_id.slug slug=item.product.category_id.parent_category.slug product_slug=item.product.slug %}">
                            <h2>{{ item.product.name }}</h2></a>
                        <p>{{ item.product.amazon_id }}</p>
                    </div>
                    <div class="product__color cart__product-block">
                        <p>{{ item.product.color }}</p>
                    </div>
                    <div class="product__quantity cart__product-block">
                        <p>{{ item.quantity }}</p>
                    </div>
                    <div class="product__amount cart__product-block">
                        <p>€ {{ item.price }}</p>
                    </div>
                    <div class="product__size cart__product-block">
                        <p>€    {{ item.subtotal }}</p>
                    </div>
                    <div class="product__amount cart__product-block">
                        <form action="{% url 'remove' %}" method="POST" class="removeForm">
                            {% csrf_token %}
                            <input type="hidden" name="id" value="{{ item.product.id }}">
                            <button type="submit" class="cart__remove-link">&#215</button>
                        </form>
                    </div>
                </div>
            {% endfor %}
                <div class="cart__total">
                    <h3>Subtotal: <span>€ {{ my_basket.total }}</span></h3>
                </div>
        </div>
        <div class="cart__button">
            <div class="cart__continue">
                <a href="{% url "categories" %}">Continue Shopping</a>
            </div>
            <div class="cart__order-button">
                <a href="{% url 'order' %}">Order now</a>
            </div>
        </div>
        {% endif %}

templates/cart/cart.html
{% extends 'base.html' %}
{% load carton_tags %}
{% block breadcrumps %}
    <div class="breadcrumbs">
        <ul class="breadcrumbs__list">
            <li class="breadcrumbs__item">
                <a href="{% url "home" %}">Home</a>
            </li>
            <li class="breadcrumbs__item">
                <a href="{% url "cart" %}">Cart</a>
            </li>
        </ul>
    </div>
{% endblock breadcrumps %}
{% block content %}
    <section class="cart" id="cartSection">
        <div class="cart__caption">
            <h1>Your shopping bag</h1>
            {% if my_basket.count == 0 %}
            <p>is empty</p>
            {% else %}
            <p>Items reserved for limited time only</p>
            {% endif %}
        </div>
        {% if my_basket.count > 0 %}
        <div class="cart__order">
            <div class="order-quality">
                <div class="order-quality__product cart__product-block">
                    <p>Product</p>
                </div>
                <div class="order-quality__description cart__product-block">
                    <p>Description</p>
                </div>
                <div class="order-quality__color cart__product-block">
                    <p>Color</p>
                </div>
                <div class="order-quality__quantity cart__product-block">
                    <p>Qty</p>
                </div>
                <div class="order-quality__amount cart__product-block">
                    <p>Amount</p>
                </div>
                <div class="order-quality__size cart__product-block">
                    <p>Subtotal</p>
                </div>
                <div class="order-quality__amount cart__product-block">
                    <p>Remove</p>
                </div>
            </div>
            {% for item in my_basket.items %}
                <div class="cart__product">
                    <div class="product__image cart__product-block">
                        <img src="/static/img/item/{{ item.product.thumbnail_image }}">
                    </div>
                    <div class="product__caption cart__product-block">
                        <a href="{% url "product" child_slug=item.product.category_id.slug slug=item.product.category_id.parent_category.slug product_slug=item.product.slug %}">
                            <h2>{{ item.product.name }}</h2></a>
                        <p>{{ item.product.amazon_id }}</p>
                    </div>
                    <div class="product__color cart__product-block">
                        <p>{{ item.product.color }}</p>
                    </div>
                    <div class="product__quantity cart__product-block">
                        <p>{{ item.quantity }}</p>
                    </div>
                    <div class="product__amount cart__product-block">
                        <p>€ {{ item.price }}</p>
                    </div>
                    <div class="product__size cart__product-block">
                        <p>€    {{ item.subtotal }}</p>
                    </div>
                    <div class="product__amount cart__product-block">
                        <form action="{% url 'remove' %}" method="POST" class="removeForm">
                            {% csrf_token %}
                            <input type="hidden" name="id" value="{{ item.product.id }}">
                            <button type="submit" class="cart__remove-link">&#215</button>
                        </form>
                    </div>
                </div>
            {% endfor %}
                <div class="cart__total">
                    <h3>Subtotal: <span>€ {{ my_basket.total }}</span></h3>
                </div>
        </div>
        <div class="cart__button">
            <div class="cart__continue">
                <a href="{% url "categories" %}">Continue Shopping</a>
            </div>
            <div class="cart__order-button">
                <a href="{% url 'order' %}">Order now</a>
            </div>
        </div>
        {% endif %}
    </section>
{% endblock content %}

templates/cart/order.html
{% extends 'base.html' %}
{% load carton_tags %}
{% block breadcrumps %}
    <div class="breadcrumbs">
        <ul class="breadcrumbs__list">
            <li class="breadcrumbs__item">
                <a href="{% url "home" %}">Home</a>
            </li>
            <li class="breadcrumbs__item">
                <a href="{% url "cart" %}">Cart</a>
            </li>
            <li class="breadcrumbs__item">
                <a href="{% url "order" %}">Order</a>
            </li>
        </ul>
    </div>
{% endblock breadcrumps %}
{% block content %}
<form class="order__wrap" method="post" action="." name="order_form" id="formOrder" novalidate>
    {% csrf_token %}
    <div class="order order--page">
{#    <section class="cart cart--order-page" id="cartSection">#}
{#        <div class="cart__caption">#}
{#            <h1>Your shopping bag</h1>#}
{#            {% if my_basket.count == 0 %}#}
{#            <p>is empty</p>#}
{#            {% else %}#}
{#            <p>Items reserved for limited time only</p>#}
{#            {% endif %}#}
{#        </div>#}
{#        {% if my_basket.count > 0 %}#}
{#        <div class="cart__order">#}
{#            <div class="order-quality">#}
{#                <div class="order-quality__product cart__product-block">#}
{#                    <p>Product</p>#}
{#                </div>#}
{#                <div class="order-quality__description cart__product-block">#}
{#                    <p>Description</p>#}
{#                </div>#}
{#                <div class="order-quality__color cart__product-block">#}
{#                    <p>Color</p>#}
{#                </div>#}
{#                <div class="order-quality__quantity cart__product-block">#}
{#                    <p>Qty</p>#}
{#                </div>#}
{#                <div class="order-quality__amount cart__product-block">#}
{#                    <p>Amount</p>#}
{#                </div>#}
{#                <div class="order-quality__size cart__product-block">#}
{#                    <p>Subtotal</p>#}
{#                </div>#}
{#                <div class="order-quality__amount cart__product-block">#}
{#                    <p>Remove</p>#}
{#                </div>#}
{#            </div>#}
{#            {% for item in my_basket.items %}#}
{#                <div class="cart__product">#}
{#                    <div class="product__image cart__product-block">#}
{#                        <img src="/dist/img/item/{{ item.product.thumbnail_image }}">#}
{#                    </div>#}
{#                    <div class="product__caption cart__product-block">#}
{#                        <a href="{% url "product" child_slug=item.product.category_id.slug slug=item.product.category_id.parent_category.slug product_slug=item.product.slug %}">#}
{#                            <h2>{{ item.product.name }}</h2></a>#}
{#                        <p>{{ item.product.amazon_id }}</p>#}
{#                    </div>#}
{#                    <div class="product__color cart__product-block">#}
{#                        <p>{{ item.product.color }}</p>#}
{#                    </div>#}
{#                    <div class="product__quantity cart__product-block">#}
{#                        <p>{{ item.quantity }}</p>#}
{#                    </div>#}
{#                    <div class="product__amount cart__product-block">#}
{#                        <p>€ {{ item.price }}</p>#}
{#                    </div>#}
{#                    <div class="product__size cart__product-block">#}
{#                        <p>€    {{ item.subtotal }}</p>#}
{#                    </div>#}
{#                    <div class="product__amount cart__product-block">#}
{#                        <form action="{% url 'remove' %}" method="POST" class="removeForm">#}
{#                            {% csrf_token %}#}
{#                            <input type="hidden" name="id" value="{{ item.product.id }}">#}
{#                            <button type="submit" class="cart__remove-link">&#215</button>#}
{#                        </form>#}
{#                    </div>#}
{#                </div>#}
{#            {% endfor %}#}
{#                <div class="cart__total">#}
{#                    <h3>Subtotal: <span>€ {{ my_basket.total }}</span></h3>#}
{#                </div>#}
{#        </div>#}
{#        <div class="cart__button">#}
{#            <div class="cart__continue">#}
{#                <a href="{% url "categories" %}">Continue Shopping</a>#}
{#            </div>#}
{#            <div class="cart__order-button">#}
{#                <a href="{% url 'order' %}" id="showShippingAddress">Order now</a>#}
{#            </div>#}
{#        </div>#}
{#        {% endif %}#}
{#    </section>#}

    <section class="shipping" id="shippingSection">
        <div class="form form--contact form--edit-account form--order-page">
            <div class="form__caption">
                <h2>Shipping address</h2>
                <p>All fields are required</p>
            </div>
            <div class="form__delivery">
                <label for="delivery">Select delivery method</label>
                <select id="delivery" name="delivery">
                    {% for method in delivery %}
                    <option value="{{ method.id }}">{{ method.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form__data">
                <div class="form form__data--name">
                    <label for="first_name">First name</label>
                    <input type="text" id="first_name" name="first_name" required value="{% if user.first_name != '' %}{{ user.first_name }}{% else %}{% endif %}">
                </div>
                <div class="form form__data--email">
                    <label for="last_name">Last name</label>
                    <input type="text" id="last_name" name="last_name" required value="{% if user.last_name != '' %}{{ user.last_name }}{% else %}{% endif %}">
                </div>
            </div>
            <div class="form__address">
                <label for="address_1">Address</label>
                <input type="text" id="address_1" required name="first_line_adress" value="{% if user.profile.first_line_adress != None %}{{ user.profile.first_line_adress }}{% else %}{% endif %}">
            </div>
            <div class="form__data">
                <div class="form form__data--name">
                    <label for="city">City</label>
                    <input id="city" type="text" name="city" required value="{% if user.profile.city != None %}{{ user.profile.city }}{% else %}{% endif %}">
                </div>
                <div class="form form__data--email">
                    <label for="zip">Postal code</label>
                    <input id="zip" type="text" required name="postal_code" value="{% if user.profile.postal_code != None %}{{ user.profile.postal_code }}{% else %}{% endif %}">
                </div>
            </div>
            <div class="form__country form__topic">
                <label for="country">Country</label>
                <select id="id_country" name="country">
                    <option value="">---------</option>
                    <option value="GB">United Kingdom</option>
                    <option value="AF">Afghanistan</option>
                    <option value="AL">Albania</option>
                    <option value="DZ">Algeria</option>
                    <option value="AS">American Samoa</option>
                    <option value="AD">Andorra</option>
                    <option value="AR">Argentina</option>
                    <option value="AM">Armenia</option>
                    <option value="AU">Australia</option>
                    <option value="AT">Austria</option>
                    <option value="BY" selected="selected">Belarus</option>
                    <option value="BE">Belgium</option>
                    <option value="BZ">Belize</option>
                    <option value="BM">Bermuda</option>
                    <option value="LT">Lithuania</option>
                    <option value="LU">Luxembourg</option>
                    <option value="RU">Russian Federation</option>
                    <option value="US">United States</option>
                </select>
            </div>
            <div class="form__address">
                <label for="email">Email</label>
                <input type="text" id="email" required name="email" value="{% if user.email != '' %}{{ user.email }}{% else %}{% endif %}">
            </div>
        <div class="cart__button cart__button--form">
            <div class="cart__order-button">
                <a href="/order/" id="showPayment">Next step</a>
            </div>
        </div>
        </div>
    </section>
    <section class="payment" id="paymentSection">
          <div class="form form--payment">
            <div class="form__caption">
                <h2>Payment options</h2>
                <p>All fields are required</p>
            </div>
            <div class="form__amount">
                <h3>Subtotal: <span>€ {{ my_basket.total }}</span></h3>
                <h3>Shipping: <span>€ 0</span></h3>
                <h3><span class="total">Total: <span>€ {{ my_basket.total }}</span></span></h3>
            </div>
            <div class="form__payment">
                <label for="payment">Select payment method</label>
                <select id="payment" name="paymentMethod">
                    {% for pay in payment %}
                    <option value="{{ pay.id }}">{{ pay.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form__input form__input--order">
                <input type="submit" value="ORDER NOW">
            </div>
        </div>
    </section>
    </div>
</form>

{% endblock content %}

templates/cart/thanks.html
{% extends 'base.html' %}
{% block breadcrumps %}
    <div class="breadcrumbs">
        <ul class="breadcrumbs__list">
            <li class="breadcrumbs__item">
                <a href="{% url 'home' %}">Home</a>
            </li>
            <li class="breadcrumbs__item">
                <a href="{% url 'cart' %}">Order</a>
            </li>
        </ul>
    </div>
{% endblock breadcrumps %}
{% block content %}
    <section class="contact">
        <div class="contact__text">
            <h1>THANK YOU FOR ORDER</h1>
            <p>We'll contact you immediately!</p>
        </div>
    </section>
{% endblock content%}